### ISSUE TITLE
Highligting issue in Idea 15.0 and 0.8.0 plugin

### ISSUE THREAD

**Issue by mostr** [vermut/intellij-ansible#32] opened 2015-12-07 12:09 UTC
Looks like code higlighting doesn't work properly, as most of the content is just regular text (comparing to YAML plugin)
![highlighting_issue](https://cloud.githubusercontent.com/assets/1169259/11626524/c4474880-9ce3-11e5-9b25-01f077cf3920.png)

**Comment by mikolak-net** [comment] 2015-12-07 12:20
Can confirm this.

Compare the built-in YAML plugin settings:

![yaml-ansible](https://cloud.githubusercontent.com/assets/1729900/11626659/d20c66ac-9ce4-11e5-8e07-e30989d05446.png)

with :

![yaml-ansible1](https://cloud.githubusercontent.com/assets/1729900/11626668/e3b952f2-9ce4-11e5-8aef-5e10b2e9d4ec.png)

It appears that it's simply a case if a small inconsistency relative to the built-in YAML plugin - whereas YAML keys are styled w.r.t. to the `Keyword` general settings, in this plugin they are styled w.r.t. to `Identifiers→Default`.

**Comment by vermut** [comment] 2016-03-14 23:17
This is a very random issue and usually I cannot reproduce on clean installs. Do you?

**Comment by mikolak-net** [comment] 2016-03-14 23:29
Can't say about clean at the moment, but it certainly seems to occur whenever a new window is spawned away from the main one.

**Comment by vermut** [comment] 2020-10-18 17:25
Probably will be fixed by next release.

**Closed by vermut** 2020-10-18 17:25 UTC
