### ISSUE TITLE
Inline content is not properly parsed

### ISSUE THREAD

**Issue by mfriedenhagen** [vermut/intellij-ansible#4] opened 2015-05-23 19:52 UTC
I sometime use inline templates:

```yaml
- name: Write JolokiaCollector.conf file
  copy:
    dest: /etc/diamond/collectors/JolokiaCollector.conf
    content: |
      host = 'localhost'
      enabled = True
      port = {{mamido_basepkg_metrics_diamond_jolokia_port}}
      {% if mamido_basepkg_metrics_diamond_jolokia_mbeans|length > 0 %}
      mbeans = '{{ mamido_basepkg_metrics_diamond_jolokia_mbeans|join("|") }}'
      {% endif %}\n
  notify: Restart diamond
  when: mamido_basepkg_metrics_diamond_jolokia_port
```

However the plugin is showing errors for this content.

**Comment by vermut** [comment] 2015-05-25 07:23
What version/build are you using? This code is not giving me errors. Parsing is far from optimal and correct, but at least it recognizes blocks and vars.

**Comment by mfriedenhagen** [comment] 2015-05-25 20:56
Hello Vermut, AFAIK I am using the latest release (0.6), I updated the example. The first letters in the block are underlined and I get a lot of hovers stating: `expected key-val pair or array item` and all lines after the first with an error have an error as well. Probably it is the best not to parse any of the inline content at all.

**Comment by vermut** [comment] 2015-05-26 09:31
My parser is far from YAML-spec complete. Maybe someone one day will replace it with SnakeYAML for example, but for now there is not much I can do.

**Comment by karlp** [comment] 2015-11-17 15:47
:+1: Getting this as well while trying to use this plugin on RAML files.

**Comment by vermut** [comment] 2016-01-04 14:03
I made a different Yaml parser plugin. It does not include any Ansible functionality but parses YAML really good. Can you [try it](https://github.com/vermut/intellij-snakeyaml/raw/master/intellij-snakeyaml.zip) and see if it works better?

**Comment by karlp** [comment] 2016-01-04 15:01
I don't see any other file type turn up in the settings->editor->file types list to use after installing the snakeyaml plugin?

**Comment by vermut** [comment] 2016-01-04 15:48
Should be "SnakeYAML". You don't see it? What version of IDE are you using?

**Comment by karlp** [comment] 2016-01-04 16:44
I can see it in plugins, but not in filetypes.  Using pycharm community, both 4.5.x and 5.0.x

**Comment by karlp** [comment] 2016-01-04 17:38
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: lv.kid.vermut.intellij.yaml.editor.YamlColorsPage PluginClassLoader[SnakeYAML plugin, 1.15.0]

I'm guessing the zip was't complete?

**Comment by vermut** [comment] 2016-01-04 22:34
Try again, version 1.15.1 (same link)

**Comment by karlp** [comment] 2016-01-05 10:31
Beautiful, works very well, fixes my problems, and pasting the snippet from the top of the ticket works fine too.  I get red squiggles under the %, but the files validate properly, with nice green ticks in the top right and no warnings on hover, I guess the red squiggle is a typo warning or something?

**Comment by vermut** [comment] 2016-01-05 12:05
Well... That's another thing. {% %} a part of Jinja2 template language and not YAML, so example above is not valid _YAML_. It becomes one after Jinja2 is finished with it.

My next step is allowing to painlessly embed Jinja2 into YAML.

**Comment by karlp** [comment] 2016-01-05 13:27
well, I think that's perfectly ok for the user to deal with.  this is _much_ better than the earlier yaml plugin! very cool thanks!

**Comment by mfriedenhagen** [comment] 2016-01-05 22:05
Hello @vermut, great work. Looks much better. I hope you have the time to incorporate this plugin into your ansible one, I really like the ability to jump to roles.

**Comment by yfried-redhat** [comment] 2016-01-07 14:04
is the snakeyaml available on PyCharm?

**Comment by vermut** [comment] 2016-01-07 17:46
Soon will be in repo. Meanwhile you can install it from zip

**Comment by soar** [comment] 2016-01-21 14:16
Please add support for multiline strings like `name: >` and `name: |` to this plugin.

**Comment by systeminsightsbuild** [comment] 2016-02-23 15:35
I've come back to the ansible plugin from very early days where it would just crash right away on our faily large project. But now its seems to work quite nicely. The only problem I have ran into is errors for when using `name: >` and `name: |`.

**Closed** 2016-03-13 22:54 UTC
Labels: help wanted, needs proper yaml
