### ISSUE TITLE
Crash when indexing yaml file

### ISSUE THREAD

**Issue by mkordas** [vermut/intellij-ansible#7] opened 2015-05-31 17:01 UTC
```
Error while indexing C:\IdeaProjects\checkstyle-contribution\checkstyle-tester\src\main\java\elasticsearch\rest-api-spec\test\indices.get_mapping\40_aliases.yaml
To reindex this file IDEA has to be restarted: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
	at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:518)
	at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:831)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getTokenStart(FlexAdapter.java:64)
	at com.intellij.lexer.DelegateLexer.getTokenStart(DelegateLexer.java:55)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenEnd(MergingLexerAdapterBase.java:59)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:86)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:397)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1675)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1623)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```
Problematic file:
```
---
"Getting mapping for aliases should return the real index as key":

  - do:
        indices.create:
          index: test_index
          body:
              mappings:
                test_type:
                  properties:
                    text:
                      type:     string
                      analyzer: whitespace

  - do:
      indices.put_alias:
        index: test_index
        name:  test_alias

  - do:
      indices.get_mapping:
        index: test_alias

  - match: {test_index.mappings.test_type.properties.text.type:     string}
  - match: {test_index.mappings.test_type.properties.text.analyzer: whitespace}

```

**Comment by vermut** [comment] 2015-05-31 17:02
All the time it is this file? Or always different like in #2?

**Comment by vermut** [comment] 2015-06-01 14:23
Cannot repeat. 
What are the versions?
Can you send my a whole project?

**Comment by mkordas** [comment] 2015-06-02 19:32
Indeed, it's always different file, so looks like duplicate of #2. The project is huge and consists of multiple open-source projects checked out to one directory:
```
Chronicle-Map
HBase
JaCoCo
Jenkins
MaterialDesignLibrary
RxJava
WildFly
android-launcher
apache-ant
apache-jsecurity
checkstyle
elasticsearch
findbugs
guava
java-design-patterns
lombok-ast
pmd
sevntu-checkstyle
spring-framework
throwing-lambdas
```

**Comment by vermut** [comment] 2015-06-02 20:47
If possible, please make a zip of the whole project and upload it somewhere. I never had the chance to reproduce this error on my projects.

**Comment by mkordas** [comment] 2015-06-04 15:56
This project contains 2 GB of source files. You can recreate it by using [launch.sh](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/launch.sh) and uncommenting/adding the project from above in [projects-to-test-on.properties](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties).

**Comment by vermut** [comment] 2015-06-12 09:29
Duplicate of #2

**Closed by vermut** 2015-06-12 09:29 UTC
Labels: duplicate
