### ISSUE TITLE
Crash indexing .yml file: pushback value was too large

### ISSUE THREAD

**Issue by jkleint** [vermut/intellij-ansible#8] opened 2015-06-01 16:46 UTC
Version 0.7.
```
Error while indexing foo.yml
To reindex this file IDEA has to be restarted: cz.juzna.intellij.neon.lexer._NeonLexer: Error: pushback value was too large
java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: pushback value was too large
	at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:518)
	at cz.juzna.intellij.neon.lexer._NeonLexer.yypushback(_NeonLexer.java:532)
	at cz.juzna.intellij.neon.lexer._NeonLexer.retryInState(_NeonLexer.java:382)
	at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:711)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
	at com.intellij.lexer.MergingLexerAdapterBase.locateToken(MergingLexerAdapterBase.java:71)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenStart(MergingLexerAdapterBase.java:52)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:78)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:397)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1675)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1623)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

```
`foo.yml` is something like this:
```
---
# Install foo.
- hosts: all
  sudo: yes
  vars:
    dir: /opt
    version: '1.2.3'

  tasks:
  - shell: creates="{{dir}}/foo-{{version}}" curl http://foo.example.org/download/1/23/foo-{{version}}.tar.gz | tar -xzC "{{dir}}"
  - file: src="{{dir}}/foo-{{version}}" dest="{{dir}}/foo" state=link
  - command: chdir={{dir}}/foo creates=foo1
  - command: chdir={{dir}}/foo/bar creates=bar make
```

**Comment by tiagodeoliveira** [comment] 2015-06-08 13:11
I did have the very same error.
Follow my yml file:

```yaml
bulkcontent:
  build: .
  links:
  - db
  - mongo
  - mongosecondary
  - mongoarbiter
  ports:
  - "40011:40011"
  - "18010:18010"
mongo:
  image: mongo
  expose:
  - "27017"
  command: mongod --smallfiles  
mongosecondary:
  image: mongo
  expose:
  - "27017"
  command: mongod --smallfiles  
mongoarbiter:
  image: mongo
  expose:
  - "27017"
  command: mongod --smallfiles  
db:
  build: ../purebros-mysql/
  expose:
  - "3306"
```

**Comment by vermut** [comment] 2015-06-09 13:34
Is it always the same file?

**Comment by azumafuji** [comment] 2015-06-10 08:05
Same error here:
```
Error while indexing main.yml
To reindex this file IDEA has to be restarted: cz.juzna.intellij.neon.lexer._NeonLexer: Error: pushback value was too large
java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: pushback value was too large
	at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:525)
	at cz.juzna.intellij.neon.lexer._NeonLexer.yypushback(_NeonLexer.java:539)
	at cz.juzna.intellij.neon.lexer._NeonLexer.retryInState(_NeonLexer.java:389)
	at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:723)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getState(FlexAdapter.java:52)
	at com.intellij.lexer.MergingLexerAdapterBase.locateToken(MergingLexerAdapterBase.java:73)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenType(MergingLexerAdapterBase.java:46)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:74)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:397)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1675)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1623)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

Always the same file 

```
---
  - name: Ensure that transparent hugepage compaction is turned off on reboot
    lineinfile: dest=/etc/rc.local regexp='^.*transparent_hugepage.*$' line='echo never > /sys/kernel/mm/transparent_hugepage/defrag'

  - name: Add MongoDB key
    sudo: yes
    tags: [mongodb]
    apt_key: id=7F0CEB10 url="http://docs.mongodb.org/10gen-gpg-key.asc" state=present

  - name: Get release informaiton
    tags: [mongodb]
    shell: "lsb_release -sc"
    register: lsbRelease
    
  - name: Add MongoDB Repository
    sudo: yes
    tags: [mongodb]
    apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{lsbRelease.stdout}}/mongodb-org/3.0 multiverse' state=present update_cache=yes

  - name: Install latest stable mongodb
    sudo: yes
    tags: [mongodb]
    apt: pkg={{ item }} state=latest
    with_items:
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools

  - name: "Update mongod.conf"
    sudo: yes
    template: src=mongod.conf dest=/etc/mongod.conf mode=644

  - name: "Ensure mongodb server is running"
    tags: [mongodb]
    sudo: yes
    action: service name=mongod enabled=yes state=started

  - name: Update MOTD script
    sudo: yes
    tags: [motd, mongodb]
    copy: src=motd.sh dest=/etc/update-motd.d/20-info-mongo owner=root group=root mode=0755
```

**Comment by vermut** [comment] 2015-06-12 09:29
Duplicate of #2

**Closed by vermut** 2015-06-12 09:29 UTC
