### ISSUE TITLE
Version 0.7.2 crashes at startup

### ISSUE THREAD

**Issue by adamatan** [vermut/intellij-ansible#12] opened 2015-06-11 07:37 UTC
Hi,
After updating the plugin, it crashes when PyCharm starts (Stacktrace below).
Please let me know if I can help with any other details/testing,
Best - and thanks for the wonderful plugin!
Adam

	Error while indexing /Users/adamatan/vioozer/devops-ansible/roles/dev/vars/main.yml
	To reindex this file IDEA has to be restarted: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
	java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
		at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:525)
		at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:838)
		at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
		at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
		at com.intellij.lexer.MergingLexerAdapterBase.locateToken(MergingLexerAdapterBase.java:71)
		at com.intellij.lexer.MergingLexerAdapterBase.getTokenType(MergingLexerAdapterBase.java:46)
		at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:74)
		at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:139)
		at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:126)
		at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:81)
		at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:75)
		at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
		at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1824)
		at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1751)
		at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1714)
		at com.intellij.util.indexing.UnindexedFilesUpdater.processFile(UnindexedFilesUpdater.java:73)
		at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:103)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:231)
		at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:911)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:241)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
		at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:236)
		at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
		at java.util.concurrent.FutureTask.run(FutureTask.java:138)
		at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
		at java.lang.Thread.run(Thread.java:695)
		at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

	java.lang.ArrayIndexOutOfBoundsException: 754
		at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:572)
		at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
		at com.intellij.lexer.FlexAdapter.getTokenStart(FlexAdapter.java:64)
		at com.intellij.lexer.DelegateLexer.getTokenStart(DelegateLexer.java:55)
		at com.intellij.lexer.MergingLexerAdapterBase.getTokenEnd(MergingLexerAdapterBase.java:59)
		at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:86)
		at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:139)
		at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:126)
		at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:81)
		at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:75)
		at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
		at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1824)
		at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1751)
		at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1714)
		at com.intellij.util.indexing.UnindexedFilesUpdater.processFile(UnindexedFilesUpdater.java:73)
		at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:103)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:231)
		at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:911)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:241)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
		at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:236)
		at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
		at java.util.concurrent.FutureTask.run(FutureTask.java:138)
		at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
		at java.lang.Thread.run(Thread.java:695)
		at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

	java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
		at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:525)
		at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:838)
		at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
		at com.intellij.lexer.FlexAdapter.getTokenStart(FlexAdapter.java:64)
		at com.intellij.lexer.DelegateLexer.getTokenStart(DelegateLexer.java:55)
		at com.intellij.lexer.MergingLexerAdapterBase.getTokenEnd(MergingLexerAdapterBase.java:59)
		at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:78)
		at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:139)
		at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:126)
		at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:81)
		at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:75)
		at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
		at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1824)
		at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1751)
		at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1714)
		at com.intellij.util.indexing.UnindexedFilesUpdater.processFile(UnindexedFilesUpdater.java:73)
		at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:103)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:231)
		at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:911)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:241)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
		at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
		at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:236)
		at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
		at java.util.concurrent.FutureTask.run(FutureTask.java:138)
		at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
		at java.lang.Thread.run(Thread.java:695)
		at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

**Comment by vermut** [comment] 2015-06-12 09:28
Duplicate of #2

**Closed by vermut** 2015-06-12 09:28 UTC
